name: installation-script-test
on: push

jobs:
  test-install-script-windows-latest:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Test windows installer in CI
        shell: pwsh
        run: |
          Invoke-Expression -Command "install.ps1"

  test-install-script-windows:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: install-v1 script does not install v2 or greater version
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          .\install-v1.ps1
          $cliVersionCmdOutput = cmd /c 'C:\ProgramData\fossa-cli\fossa.exe' '--version'
          Write-Output $cliVersionCmdOutput
          $cliVersionMajor = $cliVersionCmdOutput.Split(" ")[2][0]
          if (-Not $cliVersionMajor -eq "1") {
            Write-Output "Got: $cliVersionMajor instead!"
            exit 1
          }

          Test windows installer in CI