name: installation-script-test
on: push
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: 'sss'

  # test-install-script-windows:
  #   runs-on: 'windows-latest'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: install-v1 script does not install v2 or greater version
  #       shell: pwsh
  #       run: |
  #         Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
  #         .\install-v1.ps1
  #         $cliVersionCmdOutput = cmd /c 'C:\ProgramData\fossa-cli\fossa.exe' '--version'
  #         Write-Output $cliVersionCmdOutput
  #         $cliVersionMajor = $cliVersionCmdOutput.Split(" ")[2][0]
  #         if (-Not $cliVersionMajor -eq "1") {
  #           Write-Output "Got: $cliVersionMajor instead!"
  #           exit 1
  #         }

  #         Test windows installer in CI