name: installation-script-test
on: push

jobs:
  install-script-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install script performs installation in linux and macOs
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          .\install.ps1
          fossa.exe --version